theme = "everforest_dark"

[editor]
true-color = true
line-number = "relative"
cursorline = true

[editor.lsp]
display-progress-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
