[[language]]
name = "javascript"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server"
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  {name = "typescript-language-server", except-features = ["format"]},
  "vscode-eslint-language-server"
]

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }
auto-format = false

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = false

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
format = true
validate = "on"
experimental = { useFlatConfig = false }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.vscode-eslint-language-server.config.codeAction]
[language-server.vscode-eslint-language-server.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.vscode-eslint-language-server.config.codeAction.showDocumentation]
enable = true

[language-server.vscode-eslint-language-server.config.codeActionOnSave]
enable = false
mode = "fixAll"

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "location"
