-- require('plugins.config.nvim-tree')
require('plugins.config.colors')
-- require('plugins.config.lualine')
require('plugins.config.fidget')
require('plugins.config.telescope')
require('plugins.config.treesitter')
require('plugins.config.autopairs')
require('plugins.config.indent-blankline')
require('plugins.config.lsp')
-- require('plugins.config.cmp')
require('plugins.config.luasnip')
require('plugins.config.gitsigns')
